name: Update games
on:
  schedule:
    - cron: "0 14 * * *"
jobs:
  updateGames:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npx lerna bootstrap
      - run: npm run scrapGames --prefix ./packages/api
      - uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Run scripts/scrapGames
          branch: update-games
          title: "Update games"
          body: |
            This PR was automatically created after running the `scrapGames` scripts.
            Merging it will trigger a deployment of the API with the updated list of games.
          reviewers: zhouzi
