name: Scrap data from various sources
on:
  schedule:
    - cron: "0 9 * * *"
jobs:
  scrapGames:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn
      - run: yarn --cwd ./packages/scripts scrapGames
      - run: yarn --cwd ./packages/scripts scrapPosts
      - run: yarn --cwd ./packages/scripts createNewsletter
        env:
          SENDINBLUE_API_KEY: ${{ secrets.SENDINBLUE_API_KEY }}
      - uses: peter-evans/create-pull-request@v3
        with:
          reviewers: zhouzi
